name: CI/CD for Labor Link Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/labor-link-backend:latest

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker image rm ${{ secrets.DOCKER_USERNAME }}/labor-link-backend:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/labor-link-backend:latest
            docker stop labor-link-backend || true
            docker rm labor-link-backend || true
            docker run -d --name labor-link-backend -p 5000:5000 \
              --env-file /home/ubuntu/laborlink-backend/Backend/.env \
              ${{ secrets.DOCKER_USERNAME }}/labor-link-backend:latest
            docker ps -a
            docker logs labor-link-backend || true
